global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'kbs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kbs:8000']

  - job_name: 'qdrant'
    metrics_path: '/metrics'
    http_headers:
      api-key:
        values: ['__QDRANT_API_KEY__']
    static_configs:
      - targets: ['qdrant:6333']
